package it.water.connectors.ethereum.service;

import it.water.connectors.ethereum.api.BlockchainApi;
import it.water.connectors.ethereum.api.BlockchainSystemApi;
import it.water.connectors.ethereum.model.EthBlockchain;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.repository.service.BaseEntityServiceImpl;
import lombok.Getter;
import lombok.Setter;


/**
 * @Generated by Water Generator
 * Service Api Class for EthereumConnector entity.
 */
@FrameworkComponent
public class BlockchainServiceImpl extends BaseEntityServiceImpl<EthBlockchain> implements BlockchainApi {

    @Inject
    @Getter
    @Setter
    private BlockchainSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public BlockchainServiceImpl() {
        super(EthBlockchain.class);
    }
}
