package it.water.connectors.ethereum.service;

import it.water.connectors.ethereum.api.BlockchainRepository;
import it.water.connectors.ethereum.api.BlockchainSystemApi;
import it.water.connectors.ethereum.model.EthBlockchain;
import it.water.core.api.registry.filter.ComponentFilterBuilder;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.repository.service.BaseEntitySystemServiceImpl;
import lombok.Getter;
import lombok.Setter;


/**
 * @Generated by Water Generator
 * System Service Api Class for EthereumConnector entity.
 */
@FrameworkComponent
public class EthBlockchainSystemServiceImpl extends BaseEntitySystemServiceImpl<EthBlockchain> implements BlockchainSystemApi {
    @Inject
    @Getter
    @Setter
    private BlockchainRepository repository;

    @Inject
    @Setter
    private ComponentFilterBuilder componentFilterBuilder;

    public EthBlockchainSystemServiceImpl() {
        super(EthBlockchain.class);
    }

}