package it.water.connectors.ethereum.service;

import it.water.connectors.ethereum.api.SmartContractApi;
import it.water.connectors.ethereum.api.SmartContractSystemApi;
import it.water.connectors.ethereum.model.EthSmartContract;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.repository.service.BaseEntityServiceImpl;
import lombok.Getter;
import lombok.Setter;


/**
 * @Generated by Water Generator
 * Service Api Class for EthereumConnector entity.
 *
 */
@FrameworkComponent
public class EthSmartContractServiceImpl extends BaseEntityServiceImpl<EthSmartContract> implements SmartContractApi {

    @Inject
    @Getter
    @Setter
    private SmartContractSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public EthSmartContractServiceImpl() {
        super(EthSmartContract.class);
    }
}
