package it.water.connectors.ethereum.service;

import it.water.connectors.ethereum.api.SmartContractRepository;
import it.water.connectors.ethereum.api.SmartContractSystemApi;
import it.water.connectors.ethereum.model.EthSmartContract;
import it.water.core.api.registry.filter.ComponentFilterBuilder;
import it.water.core.interceptors.annotations.FrameworkComponent;
import it.water.core.interceptors.annotations.Inject;
import it.water.repository.service.BaseEntitySystemServiceImpl;
import lombok.Getter;
import lombok.Setter;


/**
 * @Generated by Water Generator
 * System Service Api Class for EthereumConnector entity.
 */
@FrameworkComponent
public class EthSmartContractSystemServiceImpl extends BaseEntitySystemServiceImpl<EthSmartContract> implements SmartContractSystemApi {
    @Inject
    @Getter
    @Setter
    private SmartContractRepository repository;

    @Inject
    @Setter
    private ComponentFilterBuilder componentFilterBuilder;

    public EthSmartContractSystemServiceImpl() {
        super(EthSmartContract.class);
    }

}