package it.water.connectors.ethereum.service.rest;

import it.water.connectors.ethereum.api.BlockchainApi;
import it.water.connectors.ethereum.api.rest.BlockchainRestApi;
import it.water.connectors.ethereum.model.EthBlockchain;
import it.water.core.api.service.BaseEntityApi;
import it.water.core.api.service.rest.FrameworkRestController;
import it.water.core.interceptors.annotations.Inject;
import it.water.service.rest.persistence.BaseEntityRestApi;
import lombok.Setter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * @Generated by Water Generator
 * Rest Api Class for EthereumConnector entity.
 */
@FrameworkRestController(referredRestApi = BlockchainRestApi.class)
public class EthBlockchainRestControllerImpl extends BaseEntityRestApi<EthBlockchain> implements BlockchainRestApi {
    @SuppressWarnings("java:S1068") //still mantain the variable even if not used
    private static Logger log = LoggerFactory.getLogger(EthBlockchainRestControllerImpl.class.getName());

    @Inject
    @Setter
    private BlockchainApi blockChainApi;

    @Override
    protected BaseEntityApi<EthBlockchain> getEntityService() {
        return blockChainApi;
    }

}
