
package it.water.connectors.ethereum.service.rest.spring;

import it.water.connectors.ethereum.service.rest.EthSmartContractRestControllerImpl;
import it.water.core.api.model.*;
import it.water.core.api.repository.query.*;
import it.water.connectors.ethereum.model.*;
import org.springframework.web.bind.annotation.RestController;


/**
 * @Generated by Water Generator
 * Rest Api Class for EthereumConnector entity. It just overrides method invoking super in order to let spring find web methods.
 */
@RestController
public class EthSmartContractSpringRestControllerImpl extends EthSmartContractRestControllerImpl implements EthSmartContractSpringRestApi {
    
    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public EthSmartContract save(EthSmartContract entity) {
        return super.save(entity);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public EthSmartContract update(EthSmartContract entity) {
        return super.update(entity);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public void remove(long id) {
        super.remove(id);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public EthSmartContract find(long id) {
        return super.find(id);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public PaginableResult<EthSmartContract> findAll(Integer delta, Integer page, Query filter, QueryOrder order) {
        return super.findAll(delta, page, filter, order);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public PaginableResult<EthSmartContract> findAll() {
        return super.findAll();
    }
}
