package it.water.connectors.ethereum.api;

import it.water.core.api.service.BaseEntitySystemApi;

import it.water.connectors.ethereum.model.EthSmartContract;

/**
 * @Generated by Water Generator
 * This interface defines the internally exposed methods for the entity and allows interaction with it bypassing permission system.
 * The main goals of EthereumConnectorSystemApi is to validate the entity and pass it to the persistence layer.
 *
 */
public interface SmartContractSystemApi extends BaseEntitySystemApi<EthSmartContract> {

}