package it.water.connectors.ethereum.api;

import it.water.core.api.repository.BaseRepository;
import it.water.connectors.ethereum.model.EthSmartContract;

/**
 * @Generated by Water Generator
 * Interface component for EthereumConnector Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 *
 */
public interface SmartContractRepository extends BaseRepository<EthSmartContract> {
	
}
