package it.water.connectors.ethereum.api;

import it.water.connectors.ethereum.model.EthSmartContract;
import it.water.core.api.service.BaseEntityApi;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods for the entity and allows interaction with it through a permission system.
 */
public interface SmartContractApi extends BaseEntityApi<EthSmartContract> {

}